### PR TITLE
Fix "Error tokenizing data" from get_tickers caused by Nasdaq API change

### PR DESCRIPTION
**Pull request by rikbrown**
# Background

See https://github.com/shilewenuw/get_all_tickers/issues/15

# Change

Credit to @JaisinhBhosale9712 and others in that thread who figured out the fix - this is just a PR incorporating their changes (and cleaning up some debug-ey code in those changes as well). See the above issue for discussion.

# Testing

Used `get_all_tickers` locally and now it works.

### CODE REVIEW

**Review by a-nady — APPROVED** [review]

**Comment by uriscoes** [comment]
C'mon based Quant man @shilewenuw, MERRRRRGGGEEEEEEE

**Comment by rikbrown** [comment]
wow I waited so long for an approval and now you're begging for a merge? NEVER

**Comment by rikbrown** [comment]
If we don't get a merge by next week we can consider this dead and I'll just make an "official" fork.

**Comment by uriscoes** [comment]
Alas, @rikbrown, it appears the based QUANT man @shilewenuw is MIA.

**Comment by shilewenuw** [comment]
TBH I didn't pay much attention to this project b/c I thought Nasdaq implemented measures that killed this library, so I'm surprised that this can still work after changes. Anyways, @rikbrown  is now a collaborator (once he accepts the invite).

**Comment by uriscoes** [comment]
@shilewenuw thank you for making this project and for making @rikbrown a collaborator!

**Pull request merged**
